# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Kevin Hayes Wilson
url:              http://kevinhayeswilson.com
baseurl:          /

author:
  name:           'Kevin Hayes Wilson'
  url:            http://kevinhayeswilson.com

paginate:         5

# Custom vars
version:          cc-by-sa

github:
  repo:           https://github.com/khwilson
